### ISSUE TITLE
Ability to start without block_producer

### ISSUE THREAD

**Issue by ivanlama** [koinos/koinos#13]
Most users won't have the resources to perform the pow calculations or might not be interested in mining operations.

An option to disable/enable block_producer would give users the opportunity to run without mining.

This could be achieved in several ways:

1. Add an argument to 'docker-compose up' to conditionally enable/disable the launch of the block_producer node.
2. Create seperate docker compose files for block_producer and one for the rest of the nodes

**Comment by mvandeberg** [comment]
Let's look at doing it like this: https://stackoverflow.com/questions/45680958/can-you-define-optional-docker-compose-services/61107015#61107015
