### ISSUE TITLE
New to BlockChain

### ISSUE THREAD

**Issue by webzest** [koinos/koinos#17]
Hello,

I am trying to built a blockchain for my Employer and stumbled onto your Koinos development through a Google Search.  Is there a guide that I can follow to download Koinbos and run it on one of my Windows Servers?  I used to develop in C++ a decade ago and have been focusing on Web development in C#.  I think I can find my way back after a few weeks of practicing again.  Can you please help guide me to getting started with Koinos to built a blockchain?

**Comment by webzest** [comment]
Finally got the testnet up and running...

**Comment by sgerbino** [comment]
For future reference, please see the documentation site: https://docs.koinos.io/
