### ISSUE TITLE
config container erroneously fetches koinos_descriptors.pb at runtime instead of build time

### ISSUE THREAD

**Issue by sneak** [koinos/koinos#40]
This should be part of the container build-time process (and perhaps the descriptors or their hash should be copied into the 'config' subdir of this repo) and should not be fetching from GitHub at runtime (in `run.sh`).

https://github.com/koinos/koinos/blob/master/config/run.sh#L17

There is no reason that any Koinos processes should be communicating with Microsoft/GitHub from production systems at runtime.

Additionally, there is no cryptographic verification of the contents beyond TLS to `github.com` (i.e. not end to end).

**Comment by mvandeberg** [comment]
This has been changed. `koinos_descriptors.pb` is included in the repo and mounted in to the container as a config resource.
