### ISSUE TITLE
[FEATURE]: Print version information at startup

### ISSUE THREAD

**Issue by theoreticalbts** [koinos/koinos#43]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New feature

- Embed a commit hash, commit date and Git version tag (if applicable) in the binary of each Koinos microservice.
- Add `koinos-p2p --version` (and similar for each microservice) to print the commit hash, commit date and Git version tag (if applicable) and exit.
- Print the commit hash, commit date and Git version tag (if applicable) on startup so it's hopefully present in all logs.

[This blog post](https://icinga.com/blog/2022/05/25/embedding-git-commit-information-in-go-binaries/) has information on how to embed Git commit hashes in Golang projects.

### Anything else?

I've had the situation come up several times on the latest testnet where I run a node, don't pay attention to it for some days, come back and see it's had a problem that I want to troubleshoot.  And the first step in troubleshooting is to figure out what version I'm running, and check if related changes have already been made in a newer version.

Currently, I often get stuck on this step, because it's very difficult to determine the running version of anything.  It would be quite useful to be able to just check the head of the logs, or run e.g. `koinos-p2p --version` inside the image.

**Comment by mvandeberg** [comment]
As of v1.0.0 all microservices log their version and the associated commit hash on launch. They all support `--version` as an option to view this information and then exit.
