### ISSUE TITLE
[BUG]: An unexpected error has occurred: encountered unexpected object in initial state

### ISSUE THREAD

**Issue by motoeng** [koinos/koinos#48]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Node was syncing and upon return, it appeared to no longer be connected to any peers. I exited gracefully and upon restart, caught this error.
 Logs attached.
[Logs.zip](https://github.com/koinos/koinos/files/9800964/Logs.zip)

### Environment

```markdown
- OS:
Ubuntu 20.04 LTS
```

**Comment by mvandeberg** [comment]
Closed by koinos/koinos-state-db-cpp#2
